version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_filmes
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-senha123}
      POSTGRES_DB: ${POSTGRES_DB:-filmes_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local